In [11]:
import numpy as np

In [72]:
class Cluster(object):
    def __init__(self, nodes, weights, degrees, perimeter = None, area = None):
        self.nodes = nodes.astype(float)
        self.weights = weights.astype(float)
        self.degrees = degrees #this never changes       
        if(perimeter == None):
            self.perimeter = sum(self.weights)
        else:
            self.perimeter = perimeter
        if(area == None):
            self.area = 0
        else:
            self.area = area
            
    def get_closest(self):
        temp_perimeter = self.perimeter - 2*self.weights + self.degrees
        temp_area = self.area + self.weights
        ratios = temp_area / (temp_perimeter + 0.000001) 
        next_vertex = np.argmax(ratios * np.logical_not(self.nodes))
        this_alpha = (self.area*temp_perimeter[next_vertex])/(self.perimeter*temp_area[next_vertex]) 
        return (next_vertex, temp_area[next_vertex], temp_perimeter[next_vertex], this_alpha)
    
    def add_node(self, node, weight, temp_area, temp_perimeter):
        self.nodes[node] = 1
        self.weights += weight.astype(float)
        self.perimeter = temp_perimeter
        self.area = temp_area
        

In [57]:
graph = np.array([[0,1,1,0,0,0],[1,0,1,0,0,0],[1,1,0,1,0,0],[0,0,1,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])
degrees = np.sum(graph, axis = 1) 
degrees

array([2, 2, 3, 3, 2, 2])

In [73]:
node0 = np.array([1,0,0,0,0,0])
node1 = np.array([0,1,0,0,0,0])
a = Cluster(node1,graph[1].astype(float),degrees) #nasty little bug, best deal with it twice
next_node, next_area, next_perimeter, alpha = a.get_closest()
a.add_node(next_node,graph[next_node].astype(float),next_area,next_perimeter)
next_node, next_area, next_perimeter, alpha = a.get_closest()
a.add_node(next_node,graph[next_node].astype(float),next_area,next_perimeter)
a.get_closest()

(3, 4.0, 2.0, 1.5)

In [86]:
n = len(graph)
all_nodes = np.eye(n)
clusters = [Cluster(all_nodes[i],graph[i].astype(float),degrees) for i in range(n)]

where_we_are = [0]
for i in range(6):
    here = where_we_are[-1]
    print("here",here)
    next_node, next_area, next_perimeter, alpha = clusters[here].get_closest()
    if(visited[next_node] == 1):
        print("in if")
    else:
        print("else", next_node)
        print(clusters[next_node].get_closest())
        next_node_best, not_using, not_using2, not_using3 = clusters[next_node].get_closest()
        if(clusters[here].nodes[next_node_best] == 1):
            print("match!")
            clusters[here].add_node(next_node,graph[next_node].astype(float),next_area,next_perimeter)
        else:
            print("havnt gotten here yet")
            where_we_are.append(next_node)
            

here 0
else 1
(0, 1.0, 2.0, 0.0)
match!
here 0
else 2
(0, 1.0, 3.0, 0.0)
match!
here 0
else 3
(4, 1.0, 3.0, 0.0)
havnt gotten here yet
here 3
else 4
(5, 1.0, 2.0, 0.0)
havnt gotten here yet
here 4
else 5
(4, 1.0, 2.0, 0.0)
match!
here 4
else 3
(4, 1.0, 3.0, 0.0)
match!


In [87]:
for i in range(n):
    print(clusters[i].nodes)

[ 1.  1.  1.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  1.]
