In [2]:
import numpy as np

In [3]:
class Cluster(object):
    def __init__(self, nodes, weights, degrees, perimeter = None, area = None):
        self.nodes = nodes.astype(float)
        self.weights = weights.astype(float)
        self.degrees = degrees #this never changes       
        if(perimeter == None):
            self.perimeter = sum(self.weights)
        else:
            self.perimeter = perimeter
        if(area == None):
            self.area = 0
        else:
            self.area = area
        self.parent = None
            
    def get_closest(self):
        if (self.parent == None):
            temp_perimeter = self.perimeter - 2*self.weights + self.degrees
            temp_area = self.area + self.weights
            ratios = temp_area / (temp_perimeter + 0.000001) 
            next_vertex = np.argmax(ratios * np.logical_not(self.nodes))
            this_alpha = (self.area*temp_perimeter[next_vertex])/(self.perimeter*temp_area[next_vertex]) 
            return (next_vertex, temp_area[next_vertex], temp_perimeter[next_vertex], this_alpha)
        else:
            return self.parent.get_closest()

    def add_nodes(self, node_vector, weight):
        
        self.perimeter = self.perimeter - 2*sum(self.weights*node_vector) + sum(self.degrees*node_vector)
        self.area = self.area + sum(self.weights*node_vector)
        self.weights = self.weights + weight.astype(float) 
        self.nodes = self.nodes + node_vector

        
        
        

In [5]:
graph = np.array([[0,1,1,0,0,0],[1,0,1,0,0,0],[1,1,0,1,0,0],[0,0,1,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])
degrees = np.sum(graph, axis = 1) 
n = len(graph)
all_nodes = np.eye(n)
clusters = [Cluster(all_nodes[i],graph[i].astype(float),degrees) for i in range(n)]
clustered = [0 for i in range(n)]
for i in range(n):
    print(clusters[i].nodes) 
where_we_are = [0]
for i in range(7):
    here = where_we_are[-1]
    print("here",here)
    print(clusters[here].get_closest())
    
    next_node, next_area, next_perimeter, alpha = clusters[here].get_closest()
    print("has parent", clusters[next_node].parent)
    if(clusters[next_node].parent == 1):
        print("in if")
    else: 
        #print("else", next_node)
        #print(clusters[next_node].get_closest())
        next_node_best, not_using, not_using2, not_using3 = clusters[next_node].get_closest()
        if(clusters[here].nodes[next_node_best] == 1):
            print("match!")
            clusters[here].add_nodes(clusters[next_node].nodes,clusters[next_node].weights)
            
            clusters[next_node].parent = clusters[here]
            for i in range(n):
                print(clusters[i].nodes)  
            #clustered[next_node] = 1
            #clustered[here] = 1
        else:
            print("havnt gotten here yet")
            where_we_are.append(next_node)
            
for i in range(n):
    print(clusters[i].nodes)           

[ 1.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  1.]
here 0
(1, 1.0, 2.0, 0.0)
has parent None
match!
add_nodes[ 1.  1.  0.  0.  0.  0.] [ 1.  0.  0.  0.  0.  0.] 1.0 2.0
[ 0.  1.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  1.]
here 0
(1, 1.0, 2.0, 0.0)
has parent <__main__.Cluster object at 0xb6a90e4c>
havnt gotten here yet
here 1
(1, 1.0, 2.0, 0.0)
has parent <__main__.Cluster object at 0xb6a90e4c>
match!
add_nodes[ 0.  2.  0.  0.  0.  0.] [ 0.  1.  0.  0.  0.  0.] 0.0 4.0
[ 0.  1.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  1.]
here 1


RuntimeError: maximum recursion depth exceeded in comparison